version: '3'
services:
  postgres:
    #version postgres 9.6.9
    image: postgres
    container_name: "postgres"
    restart: always
    volumes:
      - ./app:/dados/postgree/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: postgres
    ports:
      - 54320:5432

  flyway_postgree:
    image: flyway/flyway
    command: "migrate"
    volumes:
      - ./docker/postgree/migrations/config:/flyway/conf
      - ./docker/postgree/migrations/sql:/flyway/sql
    depends_on:
      - postgres

  #micro_produto:
  #  build: ./
  #  hostname: micro_produto
  #  container_name: "micro_produto"
  #  restart: always
  #  ports:
  #    - 8085:8080
  #  links:
  #    - postgres